general: # control overall operation
   load_from_scratch: True
   save_raw_dataframe: False
   save_transformed_dataframe: True
   remove_bad_values: True
   treat_rooms_as_numeric: False
   size_bin_count: 10
category_defaults: # default values to replace missing values
   categorical: missing
   continuous: 0.0
   text: missing
   date: 2019-01-01
   excluded: missing
category_invalid_value_replacements: # default values to replace invalid values
   categorical: bad_categorical
   continuous: bad_continuous
   text: bad_text
   date: bad_date
   exclude: bad_excluded
latitude_replacement: bad_latitude
longitude_replacement: bad_longitude
non_negative_continuous: # continuous columns where only non-negative values are valid
    - 'minimum_nights'
    - 'number_of_reviews'
    - 'reviews_per_month'
    - 'calculated_host_listings_count'
valid_values: # valid values for columns that have a defined set of valid values
   neighbourhood_group:
      - 'Bronx'
      - 'Brooklyn'
      - 'Queens'
      - 'Manhattan'
      - 'Staten Island'
   room_type:
      - 'Private room'
      - 'Shared room'
      - 'Entire home/apt'
file_names: # input and output file names
   input_csv: data_kaggle.csv
   pickled_input_dataframe: kl_real_estate_input.pkl
   pickled_output_dataframe: kl_real_estate_output.pkl
   